---

- name: Verify
  hosts: all
  gather_facts: no

  tasks:
  - name: check git works
    ansible.builtin.command:  # noqa: command-instead-of-module
      cmd: git version
    register: out
    changed_when: false
    failed_when:
      - not out.rc != 0
